/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package temppw;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        // run and create temp random password
        System.out.println(new TmpPwGenerator().createTmpPsWd(4, "LooWeR"));
        
    }
}